server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=1
    username: test
    password: test
    driverClassName: org.h2.Driver
    sqlScriptEncoding: UTF-8
  h2:
    console.enabled: true
    console:
      path: /h2
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:9092

springdoc:
  swagger-ui:
    path: /swagger-index.html